SCHEMA: dict = {
    "identity": {
        "title": "Identidad del servidor",
        "fields": [
            {"key": "PublicName", "type": "str", "label": "Nombre publico",
             "tip": "Como aparece en la lista publica de servidores de Steam y dentro del juego."},
            {"key": "PublicDescription", "type": "str", "label": "Descripcion publica",
             "multiline": True,
             "tip": "Descripcion visible en el navegador publico de servidores."},
            {"key": "MaxPlayers", "type": "int", "min": 1, "max": 100,
             "tip": "Maximo de jugadores online. >32 puede causar lag/desync."},
            {"key": "Password", "type": "str", "label": "Password de acceso",
             "placeholder": "Vacio = sin password",
             "tip": "Si lo pones, cualquiera que quiera unirse necesitara meterla."},
            {"key": "Public", "type": "bool", "label": "Visible en lista publica",
             "tip": "Show on the in-game browser. False = solo por IP directa."},
            {"key": "ServerWelcomeMessage", "type": "str", "label": "Mensaje de bienvenida",
             "multiline": True,
             "tip": "Mensaje al entrar al chat. Admite <LINE>."},
        ],
    },
    "rules": {
        "title": "Reglas de juego",
        "fields": [
            {"key": "Open", "type": "bool", "label": "Registro abierto",
             "tip": "Si True, cualquiera puede unirse. Si False, hay whitelist."},
            {"key": "PauseEmpty", "type": "bool", "label": "Pausar si vacio",
             "tip": "El tiempo del juego se pausa cuando no hay jugadores online."},
            {"key": "PauseDay", "type": "bool", "label": "Pausa de dia",
             "tip": "El dia se pausa cuando no hay jugadores cerca."},
            {"key": "AllowCoop", "type": "bool", "label": "Permitir coop / split screen",
             "tip": "Allow co-op/splitscreen players in this server."},
            {"key": "SleepAllowed", "type": "bool", "label": "Permitir dormir",
             "tip": "Los jugadores pueden usar 'sleep' para pasar el tiempo."},
            {"key": "SleepNeeded", "type": "bool", "label": "Sueno necesario",
             "tip": "Si True, los jugadores se cansan y NECESITAN dormir."},
            {"key": "NoFire", "type": "bool", "label": "Sin fuego",
             "tip": "Desactiva fuego (excepto hogueras)."},
            {"key": "GlobalChat", "type": "bool", "label": "Chat global",
             "tip": "Canal /all disponible para los jugadores."},
            {"key": "ChatStreams", "type": "str", "label": "Canales de chat",
             "tip": "Lista separada por comas: s,r,a,w,y,sh,f,all"},
            {"key": "DropOffWhiteListAfterDeath", "type": "bool", "label": "Quitar de whitelist al morir",
             "tip": "En servidores Open=false, los muertos no pueden crear nuevo personaje."},
            {"key": "AnnounceDeath", "type": "bool", "label": "Anunciar muertes",
             "tip": "Mensaje global en chat cuando muere un jugador."},
            {"key": "AnnounceAnimalDeath", "type": "bool", "label": "Anunciar muertes de animales",
             "tip": "Mensaje global en chat cuando muere un animal."},
            {"key": "MaxAccountsPerUser", "type": "int", "min": 0, "max": 1000,
             "tip": "Personajes por usuario Steam. 0 = sin limite."},
            {"key": "PlayerRespawnWithSelf", "type": "bool", "label": "Respawn en sitio de muerte",
             "tip": "Permite respawnear en el sitio donde moriste."},
            {"key": "PlayerRespawnWithOther", "type": "bool", "label": "Respawn con otro jugador",
             "tip": "Permite respawnear donde esta otro jugador (split screen)."},
        ],
    },
    "pvp": {
        "title": "PvP y seguridad",
        "fields": [
            {"key": "PVP", "type": "bool", "label": "PvP",
             "tip": "Los jugadores pueden herir y matar a otros jugadores."},
            {"key": "PVPLogToolChat", "type": "bool", "label": "Log PvP en chat admin",
             "tip": "Las muertes PvP aparecen en chat de admin."},
            {"key": "PVPLogToolFile", "type": "bool", "label": "Log PvP en archivo",
             "tip": "Las muertes PvP se guardan en archivo de log."},
            {"key": "SafetySystem", "type": "bool", "label": "Sistema de seguridad",
             "tip": "PvP opt-in: los jugadores activan/desactivan PvP individualmente."},
            {"key": "ShowSafety", "type": "bool", "label": "Mostrar icono PvP",
             "tip": "Icono de calavera sobre jugadores en modo PvP."},
            {"key": "SafetyToggleTimer", "type": "int", "min": 0, "max": 1000,
             "tip": "Segundos para activar/desactivar PvP. Default: 2"},
            {"key": "SafetyCooldownTimer", "type": "int", "min": 0, "max": 1000,
             "tip": "Cooldown entre toggles. Default: 3"},
            {"key": "PVPMeleeDamageModifier", "type": "float", "min": 0, "max": 500, "step": 1,
             "tip": "Multiplicador danio melee PvP. Default: 30"},
            {"key": "PVPFirearmDamageModifier", "type": "float", "min": 0, "max": 500, "step": 1,
             "tip": "Multiplicador danio armas de fuego PvP. Default: 50"},
            {"key": "CarEngineAttractionModifier", "type": "float", "min": 0, "max": 10, "step": 0.05,
             "tip": "Menor = menos zombis atraidos por coches. Default: 0.5"},
            {"key": "PlayerBumpPlayer", "type": "bool", "label": "Empujar jugadores",
             "tip": "Los jugadores pueden empujarse al correr."},
            {"key": "PVPMeleeWhileHitReaction", "type": "bool", "label": "Melee en hit-react",
             "tip": "Permite atacar otra vez mientras dura la animacion de danio."},
            {"key": "SneakModeHideFromOtherPlayers", "type": "bool", "label": "Sigilo oculta",
             "tip": "Modo sigilo oculta al jugador de otros."},
        ],
    },
    "voice_chat": {
        "title": "Voz y Discord",
        "fields": [
            {"key": "VoiceEnable", "type": "bool", "label": "VOIP",
             "tip": "Activa proximidad de voz."},
            {"key": "VoiceMinDistance", "type": "float", "min": 0, "max": 100000, "step": 1,
             "tip": "Distancia minima de audibilidad (tiles). Default: 10"},
            {"key": "VoiceMaxDistance", "type": "float", "min": 0, "max": 100000, "step": 1,
             "tip": "Distancia maxima (tiles). Default: 100"},
            {"key": "Voice3D", "type": "bool", "label": "Audio 3D",
             "tip": "Audio direccional (izq/der)."},
            {"key": "SpeedLimit", "type": "float", "min": 10, "max": 150, "step": 1,
             "tip": "Limite de velocidad (mph). Default: 70"},
            {"key": "DiscordEnable", "type": "bool", "label": "Bridge Discord",
             "tip": "Habilita integracion con Discord."},
            {"key": "DiscordToken", "type": "str", "label": "Token del bot Discord",
             "tip": "Token del bot Discord. Cadena larga."},
            {"key": "DiscordChatChannel", "type": "str", "label": "Canal chat",
             "tip": "Nombre del canal donde ira el chat del juego."},
            {"key": "DiscordLogChannel", "type": "str", "label": "Canal logs"},
            {"key": "DiscordCommandChannel", "type": "str", "label": "Canal comandos"},
        ],
    },
    "world_save": {
        "title": "Mundo y guardado",
        "fields": [
            {"key": "SaveWorldEveryMinutes", "type": "int", "min": 0, "max": 1000000,
             "tip": "Minutos entre auto-save del mundo. 0 = solo al desconectarse todos."},
            {"key": "MapRemotePlayerVisibility", "type": "int", "min": 1, "max": 4,
             "tip": "1=Ocultos 2=Amigos 3=Amigos+cercanos 4=Todos"},
            {"key": "LoginQueueEnabled", "type": "bool", "label": "Cola de login",
             "tip": "Habilita cola cuando el server esta lleno."},
            {"key": "LoginQueueConnectTimeout", "type": "int", "min": 20, "max": 1200,
             "tip": "Segundos de espera antes de expulsar de la cola. Default: 60"},
            {"key": "MaxSafezoneSize", "type": "int", "min": 0, "max": 100000, "step": 500,
             "tip": "Tamano maximo de safezone (tiles cuadrados). Default: 20000."},
            {"key": "BloodSplatLifespanDays", "type": "int", "min": 0, "max": 365,
             "tip": "Dias antes de que los charcos de sangre desaparezcan. 0=nunca."},
            {"key": "ItemNumbersLimitPerContainer", "type": "int", "min": 0, "max": 9000,
             "tip": "Total de items por contenedor. 0=sin limite (cuidado: cuenta clavos individuales)."},
            {"key": "RemovePlayerCorpsesOnCorpseRemoval", "type": "bool", "label": "Borrar cadaveres de jugadores",
             "tip": "Borrar cadaveres de jugadores al limpiarse los normales."},
            {"key": "TrashDeleteAll", "type": "bool", "label": "Borrar todo en cubos",
             "tip": "Permite vaciar cubos de basura de un click."},
            {"key": "DisableVehicleTowing", "type": "bool", "label": "Sin remolque de coches"},
            {"key": "AllowDestructionBySledgehammer", "type": "bool", "label": "Destruir con maza",
             "tip": "Los jugadores pueden destruir el mundo con maza."},
            {"key": "SledgehammerOnlyInSafehouse", "type": "bool", "label": "Maza solo en safehouse",
             "tip": "Solo se puede usar maza dentro de un safehouse propio."},
            {"key": "SpawnItems", "type": "str", "label": "Items iniciales",
             "placeholder": "Base.Axe,Base.Bag",
             "tip": "Items que reciben los jugadores al crear personaje."},
            {"key": "SpawnPoint", "type": "str", "label": "Spawn forzado",
             "placeholder": "0,0,0",
             "tip": "Coordenadas donde TODOS spawnean. 0,0,0 = deshabilitado."},
        ],
    },
    "safehouse": {
        "title": "Safehouses",
        "fields": [
            {"key": "PlayerSafehouse", "type": "bool", "label": "Safehouse por jugadores",
             "tip": "Cualquier jugador puede reclamar safehouses."},
            {"key": "AdminSafehouse", "type": "bool", "label": "Safehouse solo admins",
             "tip": "Solo admins pueden reclamar safehouses."},
            {"key": "SafehouseAllowTrepass", "type": "bool", "label": "Entrada sin invitacion",
             "tip": "No-miembros pueden entrar al safehouse."},
            {"key": "SafehouseAllowFire", "type": "bool", "label": "Permitir fuego",
             "tip": "El fuego puede danar el safehouse."},
            {"key": "SafehouseAllowLoot", "type": "bool", "label": "Permitir loot",
             "tip": "No-miembros pueden coger objetos del safehouse."},
            {"key": "SafehouseAllowRespawn", "type": "bool", "label": "Respawn en safehouse",
             "tip": "Los jugadores respawnearan en el safehouse."},
            {"key": "SafehouseAllowNonResidential", "type": "bool", "label": "Permitir no-residenciales",
             "tip": "Permite reclamar tiendas, fabricas, etc."},
            {"key": "SafehouseDisableDisguises", "type": "bool", "label": "Sin disfraz en safehouse"},
            {"key": "SafehouseDaySurvivedToClaim", "type": "int", "min": 0, "max": 1000,
             "tip": "Dias in-game para poder reclamar. Default: 0"},
            {"key": "SafeHouseRemovalTime", "type": "int", "min": 0, "max": 100000, "step": 12,
             "tip": "Horas reales sin visitar -> expulsado del safehouse. Default: 144"},
            {"key": "DisableSafehouseWhenOwnerConnected", "type": "bool", "label": "Inseguro con dueno",
             "tip": "El safehouse se vuelve inseguro cuando el dueno esta conectado."},
            {"key": "SafehousePreventsLootRespawn", "type": "bool", "label": "Sin respawn en safehouses",
             "tip": "Edificios reclamados no respawnean loot."},
        ],
    },
    "rcon_anticheat": {
        "title": "RCON y anti-cheat",
        "fields": [
            {"key": "RCONPort", "type": "int", "min": 0, "max": 65535,
             "tip": "Puerto RCON (consola remota). Default: 27015"},
            {"key": "RCONPassword", "type": "str", "label": "Password RCON",
             "tip": "Password para RCON. Si vacio, RCON desactivado."},
            {"key": "AntiCheatSafety", "type": "int", "min": 0, "max": 100,
             "tip": "Anti-cheat del sistema de seguridad PvP. 0=off, 4=maximo."},
            {"key": "AntiCheatMovement", "type": "int", "min": 0, "max": 100,
             "tip": "Anti-cheat de movimiento. 0=off, 4=maximo."},
            {"key": "AntiCheatHit", "type": "int", "min": 0, "max": 100,
             "tip": "Anti-cheat de impactos. 0=off, 4=maximo."},
            {"key": "AntiCheatPacket", "type": "int", "min": 0, "max": 100,
             "tip": "Anti-cheat de paquetes. 0=off, 4=maximo."},
            {"key": "AntiCheatPermission", "type": "int", "min": 0, "max": 100,
             "tip": "Anti-cheat de permisos. 0=off, 2=maximo."},
            {"key": "AntiCheatXP", "type": "int", "min": 0, "max": 100,
             "tip": "Anti-cheat de XP. 0=off, 2=maximo."},
            {"key": "AntiCheatSafeHouse", "type": "int", "min": 0, "max": 100,
             "tip": "Anti-cheat de safehouse. 0=off, 2=maximo."},
            {"key": "AntiCheatPlayer", "type": "int", "min": 0, "max": 100,
             "tip": "Anti-cheat de jugadores. 0=off, 2=maximo."},
            {"key": "AntiCheatChecksum", "type": "int", "min": 0, "max": 100,
             "tip": "Anti-cheat de checksum. 0=off, 4=maximo."},
            {"key": "AntiCheatItem", "type": "int", "min": 0, "max": 100,
             "tip": "Anti-cheat de items. 0=off, 4=maximo."},
            {"key": "MaxPacketsPerSecond", "type": "int", "min": 100, "max": 1000,
             "tip": "Limite de paquetes/seg. Default: 300."},
            {"key": "DisableScoreboard", "type": "bool", "label": "Sin scoreboard",
             "tip": "Desactiva la lista de jugadores (tecla Tab)."},
            {"key": "HideAdminsInPlayerList", "type": "bool", "label": "Ocultar admins"},
            {"key": "BadWordPolicy", "type": "int", "min": 1, "max": 4,
             "tip": "1=ban 2=kick 3=log 4=mute"},
        ],
    },
    "logs_backups": {
        "title": "Logs y backups",
        "fields": [
            {"key": "BackupsCount", "type": "int", "min": 1, "max": 300,
             "tip": "Cuantas copias de seguridad mantener. Default: 5"},
            {"key": "BackupsOnStart", "type": "bool", "label": "Backup al arrancar",
             "tip": "Crear un backup cada vez que arranca el server."},
            {"key": "BackupsOnVersionChange", "type": "bool", "label": "Backup al cambiar version",
             "tip": "Backup cuando el server actualiza de version."},
            {"key": "BackupsPeriod", "type": "int", "min": 0, "max": 1500,
             "tip": "Minutos entre backups automaticos. 0=deshabilitado."},
            {"key": "DoLuaChecksum", "type": "bool", "label": "Checksum Lua",
             "tip": "Kick a clientes con archivos Lua distintos."},
            {"key": "SteamScoreboard", "type": "bool", "label": "Scoreboard Steam",
             "tip": "Mostrar avatares y nombres Steam en la lista de jugadores."},
            {"key": "SteamVAC", "type": "bool", "label": "Steam VAC",
             "tip": "Activa VAC (Valve Anti-Cheat)."},
            {"key": "UPnP", "type": "bool", "label": "UPnP",
             "tip": "Intenta abrir puertos automaticamente via UPnP."},
            {"key": "MultiplayerStatisticsPeriod", "type": "int", "min": 0, "max": 10,
             "tip": "Segundos entre estadisticas. 0=deshabilitado. Default: 1"},
            {"key": "ChatMessageCharacterLimit", "type": "int", "min": 64, "max": 1024,
             "tip": "Limite de caracteres por mensaje. Default: 200"},
            {"key": "ChatMessageSlowModeTime", "type": "int", "min": 1, "max": 30,
             "tip": "Segundos entre mensajes por jugador. Default: 3"},
            {"key": "Faction", "type": "bool", "label": "Facciones",
             "tip": "Permite crear facciones."},
            {"key": "FactionDaySurvivedToCreate", "type": "int", "min": 0, "max": 1000,
             "tip": "Dias in-game para poder crear faccion. Default: 0"},
            {"key": "FactionPlayersRequiredForTag", "type": "int", "min": 1, "max": 100,
             "tip": "Miembros requeridos en faccion para tag. Default: 1"},
            {"key": "server_browser_announced_ip", "type": "str", "label": "IP anunciada",
             "tip": "Si tienes varias IPs, fuerza una concreta para anunciar."},
        ],
    },
}


def get_keys(category: str) -> list[str]:
    return [f["key"] for f in SCHEMA[category]["fields"]]


def normalize_bool(value) -> str:
    return "true" if str(value).lower() == "true" else "false"
